# Generated by Django 4.0.6 on 2023-08-11 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devchat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='member',
            field=models.ManyToManyField(blank=True, null=True, related_name='groups', to='devchat.profile'),
        ),
    ]
